# Generated by Django 3.1.5 on 2021-04-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_news', models.ImageField(upload_to='news/')),
                ('date_news', models.DateField(max_length=70)),
                ('description_news', models.CharField(max_length=100)),
                ('title_news', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
