# Generated by Django 3.1.5 on 2021-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description_news',
            field=models.CharField(max_length=1000),
        ),
    ]
