# Generated by Django 3.1.5 on 2021-04-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screening.screening'),
        ),
    ]
