# Generated by Django 3.1.5 on 2021-03-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_time', models.CharField(max_length=70)),
                ('date_film', models.DateField(max_length=70)),
                ('price', models.IntegerField()),
                ('branch_mpei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('movie_mpei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
