# Generated by Django 3.1.5 on 2021-04-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='number',
            new_name='seat_mpei',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AddField(
            model_name='seat',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='screening_mpei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.screening'),
        ),
    ]
