# Generated by Django 3.1.5 on 2021-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=70)),
                ('genre', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('country', models.CharField(max_length=70, null=True)),
                ('tagline', models.TextField(max_length=270, null=True)),
                ('actor', models.TextField(max_length=250, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_premier', models.DateField(max_length=70, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
