# Generated by Django 3.1.5 on 2021-03-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.CharField(max_length=70),
        ),
    ]
