# Generated by Django 3.1.5 on 2021-01-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210117_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.DateField(max_length=40),
        ),
    ]
