# Generated by Django 3.1.5 on 2021-04-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='quantum',
            field=models.IntegerField(null=True),
        ),
    ]
