# Generated by Django 3.1.5 on 2021-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_quantum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='quantum',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='seats',
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
